#!/bin/sh

#GIT_WORK_TREE=$GIT_DIR/../blue-www/ git checkout -f

echo "post-receive hook of blue slice called"
docker pull localhost:5000/ncsu:latest
docker stop blue-app
docker rm blue-app
docker run -p 8080:8080 -d --name blue-app localhost:5000/ncsu:latest
